/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;

import Controladores.ControladorEstoque;
import Controladores.ControladorFuncionarios;
import Controladores.ControladorLoja;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author marco
 */
public  class Tela1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela1
     */
    
        private Tela2 Tela2;
        private Tela3 Tela3;
        private Tela4 Tela4;
        private Tela5 Tela5;
        private Tela6 Tela6;
        private Tela7 Tela7;
        private Tela8 Tela8;
        private Tela9 Tela9;
        private Tela10 Tela10;
        private Tela11 Tela11;
        
        ControladorEstoque ce = new ControladorEstoque();
        ControladorFuncionarios cf = new ControladorFuncionarios();
        ControladorLoja cl = new ControladorLoja();
    
    public Tela1() {
       
         Tela2 = new Tela2(this);
         Tela3 = new Tela3(this);
         Tela4 = new Tela4(this, cl);
         Tela5 = new Tela5(this, ce);;
         Tela6 = new Tela6(this, cf);;
         Tela7 = new Tela7(this, ce);;
         Tela8 = new Tela8(this, ce);;
         Tela9 = new Tela9(this, cf);;
         Tela10 = new Tela10(this, ce);;
         Tela11 = new Tela11(this, ce);;
        
        
        initComponents();
        
        OuvidorButton ouvidor = new OuvidorButton();
        jButton4.addActionListener(ouvidor);
        jButton3.addActionListener(ouvidor);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loja de carros");

        jButton4.setText("VENDEDOR");

        jButton3.setText("GERENTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // AQUI//
    private class OuvidorButton implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
           
            if (e.getSource() == jButton3){
            Tela2.setVisible(true);
            }
            else {
                Tela3.setVisible(true);
            }
            setVisible(false);
        }
        
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the Tela2
     */
    public Tela2 getTela2() {
        return Tela2;
    }

    /**
     * @param Tela2 the Tela2 to set
     */
    public void setTela2(Tela2 Tela2) {
        this.Tela2 = Tela2;
    }

    /**
     * @return the Tela3
     */
    public Tela3 getTela3() {
        return Tela3;
    }

    /**
     * @param Tela3 the Tela3 to set
     */
    public void setTela3(Tela3 Tela3) {
        this.Tela3 = Tela3;
    }

    /**
     * @return the Tela4
     */
    public Tela4 getTela4() {
        return Tela4;
    }

    /**
     * @param Tela4 the Tela4 to set
     */
    public void setTela4(Tela4 Tela4) {
        this.Tela4 = Tela4;
    }

    /**
     * @return the Tela5
     */
    public Tela5 getTela5() {
        return Tela5;
    }

    /**
     * @param Tela5 the Tela5 to set
     */
    public void setTela5(Tela5 Tela5) {
        this.Tela5 = Tela5;
    }

    /**
     * @return the Tela6
     */
    public Tela6 getTela6() {
        return Tela6;
    }

    /**
     * @param Tela6 the Tela6 to set
     */
    public void setTela6(Tela6 Tela6) {
        this.Tela6 = Tela6;
    }

    /**
     * @return the Tela7
     */
    public Tela7 getTela7() {
        return Tela7;
    }

    /**
     * @param Tela7 the Tela7 to set
     */
    public void setTela7(Tela7 Tela7) {
        this.Tela7 = Tela7;
    }

    /**
     * @return the Tela8
     */
    public Tela8 getTela8() {
        return Tela8;
    }

    /**
     * @param Tela8 the Tela8 to set
     */
    public void setTela8(Tela8 Tela8) {
        this.Tela8 = Tela8;
    }

    /**
     * @return the Tela9
     */
    public Tela9 getTela9() {
        return Tela9;
    }

    /**
     * @param Tela9 the Tela9 to set
     */
    public void setTela9(Tela9 Tela9) {
        this.Tela9 = Tela9;
    }

    /**
     * @return the Tela10
     */
    public Tela10 getTela10() {
        return Tela10;
    }

    /**
     * @param Tela10 the Tela10 to set
     */
    public void setTela10(Tela10 Tela10) {
        this.Tela10 = Tela10;
    }

    /**
     * @return the Tela11
     */
    public Tela11 getTela11() {
        return Tela11;
    }

    /**
     * @param Tela11 the Tela11 to set
     */
    public void setTela11(Tela11 Tela11) {
        this.Tela11 = Tela11;
    }
}
